############## GCM

Reports/Saves_for_figures/jagsfit_Mu_GCM.rds: Reports/Scripts_for_figures/compute_fit_EstimateMuGCM.R
	Rscript Reports/Scripts_for_figures/compute_fit_EstimateMuGCM.R
	
Reports/Saves_for_figures/mcmc_chain_Mu_GCM.csv: Reports/Saves_for_figures/jagsfit_Mu_GCM.rds Reports/Scripts_for_figures/SaveChainGCM.R
	Rscript Reports/Scripts_for_figures/SaveChainGCM.R

Reports/Figures/prior_posterior_mu_GCM_context2.pdf: Reports/Saves_for_figures/jagsfit_Mu_GCM.rds Reports/Scripts_for_figures/plot_prior_posterior_mu_GCM_context2.R
	Rscript Reports/Scripts_for_figures/plot_prior_posterior_mu_GCM_context2.R
	
Reports/Figures/GCM_reparam_posterior_gamma.pdf: Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better.R Reports/Saves_for_figures/jagsfit_Mu_GCM.rds
	Rscript Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better.R

Reports/Figures/GCM_reparam_posterior_y.pdf: Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better.R Reports/Saves_for_figures/jagsfit_Mu_GCM.rds
	Rscript Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better.R

Reports/Saves_for_figures/posterior_predictive_mu_GCM.rds: Reports/Scripts_for_figures/compute_posterior_predictive_mu_GCM.R Reports/Saves_for_figures/jagsfit_Mu_GCM.rds Reports/Scripts_for_figures/n_samples_predictive_check.R
	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_GCM.R
	
Reports/Figures/posterior_predictive_check_mu_GCM.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_GCM.R Reports/Saves_for_figures/posterior_predictive_mu_GCM.rds
	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_GCM.R

	
GCM_pdf: Reports/Figures/prior_posterior_mu_GCM_context2.pdf Reports/Figures/GCM_reparam_posterior_gamma.pdf Reports/Figures/GCM_reparam_posterior_y.pdf  Reports/Figures/posterior_predictive_check_mu_GCM.pdf

GCM: GCM_pdf Reports/Saves_for_figures/mcmc_chain_Mu_GCM.csv

################ Saturation


Reports/Saves_for_figures/jagsfit_Mu_saturated.rds:  Reports/Scripts_for_figures/compute_fit_EstimateMuSaturated.R
	Rscript Reports/Scripts_for_figures/compute_fit_EstimateMuSaturated.R

Reports/Saves_for_figures/mcmc_chain_Mu_saturation.csv: Reports/Saves_for_figures/jagsfit_Mu_saturated.rds Reports/Scripts_for_figures/SaveChainSaturation.R
	Rscript Reports/Scripts_for_figures/SaveChainSaturation.R
	
Reports/Figures/Mu_saturated_posterior_theta4.pdf: Reports/Saves_for_figures/jagsfit_Mu_saturated.rds Reports/Scripts_for_figures/plot_posterior_theta4_mu_saturated.R
	Rscript Reports/Scripts_for_figures/plot_posterior_theta4_mu_saturated.R
	
Reports/Figures/Mu_saturated_posterior_theta4_reparam.pdf: Reports/Saves_for_figures/jagsfit_Mu_saturated.rds Reports/Scripts_for_figures/plot_posterior_theta4_reparam_mu_saturated.R
	Rscript Reports/Scripts_for_figures/plot_posterior_theta4_reparam_mu_saturated.R
	
Reports/Saves_for_figures/posterior_predictive_mu_saturated.rds: Reports/Saves_for_figures/jagsfit_Mu_saturated.rds Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated.R Reports/Scripts_for_figures/n_samples_predictive_check.R
	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated.R
	
Reports/Figures/posterior_predictive_check_mu_saturated.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated.R Reports/Saves_for_figures/posterior_predictive_mu_saturated.rds
	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated.R
	
Reports/Figures/mu_correlation_saturation_model.pdf: Reports/Scripts_for_figures/plot_mu_correlation_saturation.R Reports/Saves_for_figures/jagsfit_Mu_saturated.rds 
	Rscript Reports/Scripts_for_figures/plot_mu_correlation_saturation.R

Reports/Saves_for_figures/posterior_predictive_mu_saturated_no_PolC_input_theta4.rds: Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_no_PolC.R Reports/Saves_for_figures/jagsfit_Mu_saturated.rds Reports/Scripts_for_figures/n_samples_predictive_check.R
	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_no_PolC.R	

Reports/Figures/posterior_predictive_check_mu_saturated_no_PolC_input_theta4.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_no_PolC.R Reports/Saves_for_figures/posterior_predictive_mu_saturated_no_PolC_input_theta4.rds
	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_no_PolC.R

Saturation_pdf: Reports/Figures/Mu_saturated_posterior_theta4.pdf Reports/Figures/mu_correlation_saturation_model.pdf Reports/Figures/Mu_saturated_posterior_theta4_reparam.pdf Reports/Figures/posterior_predictive_check_mu_saturated.pdf Reports/Figures/posterior_predictive_check_mu_saturated_no_PolC_input_theta4.pdf
	
Saturation: Saturation_pdf Reports/Saves_for_figures/jagsfit_Mu_saturated.rds Reports/Saves_for_figures/mcmc_chain_Mu_saturation.csv

################## PolC from MMR

Reports/Saves_for_figures/jagsfit_Mu_PolC_from_MMR.rds: Reports/Scripts_for_figures/compute_fit_EstimateMu_PolC_from_MMR.R
	Rscript Reports/Scripts_for_figures/compute_fit_EstimateMu_PolC_from_MMR.R
	
Reports/Saves_for_figures/posterior_predictive_mu_PolC_from_MMR.rds: Reports/Scripts_for_figures/compute_posterior_predictive_mu_PolC_from_MMR.R Reports/Saves_for_figures/jagsfit_Mu_PolC_from_MMR.rds
	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_PolC_from_MMR.R

Reports/Figures/prior_posterior_rho_PolC_from_MMR.pdf: Reports/Scripts_for_figures/plot_prior_posterior_rho_PolC_from_MMR.R Reports/Saves_for_figures/jagsfit_Mu_PolC_from_MMR.rds
	Rscript Reports/Scripts_for_figures/plot_prior_posterior_rho_PolC_from_MMR.R

Reports/Figures/posterior_predictive_check_mu_PolC_from_MMR.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_PolC_from_MMR.R Reports/Saves_for_figures/posterior_predictive_mu_PolC_from_MMR.rds Reports/Scripts_for_figures/n_samples_predictive_check.R
	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_PolC_from_MMR.R

PolC_from_MMR_pdf: Reports/Figures/prior_posterior_rho_PolC_from_MMR.pdf Reports/Figures/posterior_predictive_check_mu_PolC_from_MMR.pdf

########### Raw data
Reports/Saves_for_figures/raw_mutation_accumulation_data_Irene.csv: Reports/Scripts_for_figures/SaveRawData.R
	Rscript Reports/Scripts_for_figures/SaveRawData.R
	
	
##### DmutS3610

############## GCM_DmutS3610

Reports/Saves_for_figures/jagsfit_Mu_GCM_DmutS3610.rds: Reports/Scripts_for_figures/compute_fit_EstimateMuGCM_DmutS3610.R
	Rscript Reports/Scripts_for_figures/compute_fit_EstimateMuGCM_DmutS3610.R
	
Reports/Saves_for_figures/mcmc_chain_Mu_GCM_DmutS3610.csv: Reports/Saves_for_figures/jagsfit_Mu_GCM_DmutS3610.rds Reports/Scripts_for_figures/SaveChainGCM_DmutS3610.R
	Rscript Reports/Scripts_for_figures/SaveChainGCM_DmutS3610.R

#Reports/Figures/prior_posterior_mu_GCM_context2.pdf: Reports/Saves_for_figures/jagsfit_Mu_GCM.rds Reports/Scripts_for_figures/plot_prior_posterior_mu_GCM_context2.R
#	Rscript Reports/Scripts_for_figures/plot_prior_posterior_mu_GCM_context2.R
	
#Reports/Figures/GCM_reparam_posterior_gamma.pdf: Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better.R Reports/Saves_for_figures/jagsfit_Mu_GCM.rds
#	Rscript Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better.R

Reports/Figures/GCM_reparam_posterior_y_DmutS3610.pdf: Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better_DmutS3610.R Reports/Saves_for_figures/jagsfit_Mu_GCM_DmutS3610.rds
	Rscript Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better_DmutS3610.R

Reports/Saves_for_figures/posterior_predictive_mu_GCM_DmutS3610.rds: Reports/Scripts_for_figures/compute_posterior_predictive_mu_GCM_DmutS3610.R Reports/Saves_for_figures/jagsfit_Mu_GCM_DmutS3610.rds Reports/Scripts_for_figures/n_samples_predictive_check.R
	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_GCM_DmutS3610.R
	
Reports/Figures/posterior_predictive_check_mu_GCM_DmutS3610.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_GCM_DmutS3610.R Reports/Saves_for_figures/posterior_predictive_mu_GCM_DmutS3610.rds
	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_GCM_DmutS3610.R

	
GCM_DmutS3610_pdf: Reports/Figures/GCM_reparam_posterior_y_DmutS3610.pdf Reports/Figures/posterior_predictive_check_mu_GCM_DmutS3610.pdf

GCM_DmutS3610: Reports/Saves_for_figures/mcmc_chain_Mu_GCM.csv GCM_DmutS3610_pdf

################ Saturation_DmutS3610

Reports/Saves_for_figures/jagsfit_Mu_saturated_DmutS3610.rds:  Reports/Scripts_for_figures/compute_fit_EstimateMuSaturated_DmutS3610.R
	Rscript Reports/Scripts_for_figures/compute_fit_EstimateMuSaturated_DmutS3610.R

Reports/Saves_for_figures/mcmc_chain_Mu_saturation_DmutS3610.csv: Reports/Saves_for_figures/jagsfit_Mu_saturated_DmutS3610.rds Reports/Scripts_for_figures/SaveChainSaturation_DmutS3610.R
	Rscript Reports/Scripts_for_figures/SaveChainSaturation_DmutS3610.R
	
Reports/Figures/Mu_saturated_posterior_theta4_DmutS3610.pdf: Reports/Saves_for_figures/jagsfit_Mu_saturated_DmutS3610.rds Reports/Scripts_for_figures/plot_posterior_theta4_mu_saturated_DmutS3610.R
	Rscript Reports/Scripts_for_figures/plot_posterior_theta4_mu_saturated_DmutS3610.R
	
Reports/Figures/Mu_saturated_posterior_theta4_reparam_DmutS3610.pdf: Reports/Saves_for_figures/jagsfit_Mu_saturated_DmutS3610.rds Reports/Scripts_for_figures/plot_posterior_theta4_reparam_mu_saturated_DmutS3610.R
	Rscript Reports/Scripts_for_figures/plot_posterior_theta4_reparam_mu_saturated_DmutS3610.R
	
Reports/Saves_for_figures/posterior_predictive_mu_saturated_DmutS3610.rds: Reports/Saves_for_figures/jagsfit_Mu_saturated_DmutS3610.rds Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_DmutS3610.R Reports/Scripts_for_figures/n_samples_predictive_check.R
	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_DmutS3610.R
	
Reports/Figures/posterior_predictive_check_mu_saturated_DmutS3610.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_DmutS3610.R Reports/Saves_for_figures/posterior_predictive_mu_saturated_DmutS3610.rds
	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_DmutS3610.R
	
Reports/Figures/mu_correlation_saturation_model_DmutS3610.pdf: Reports/Scripts_for_figures/plot_mu_correlation_saturation_DmutS3610.R Reports/Saves_for_figures/jagsfit_Mu_saturated_DmutS3610.rds 
	Rscript Reports/Scripts_for_figures/plot_mu_correlation_saturation_DmutS3610.R

Reports/Saves_for_figures/posterior_predictive_mu_saturated_no_PolC_input_theta4_DmutS3610.rds: Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_no_PolC_DmutS3610.R Reports/Saves_for_figures/jagsfit_Mu_saturated_DmutS3610.rds Reports/Scripts_for_figures/n_samples_predictive_check.R
	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_no_PolC_DmutS3610.R	

Reports/Figures/posterior_predictive_check_mu_saturated_no_PolC_input_theta4_DmutS3610.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_no_PolC_DmutS3610.R Reports/Saves_for_figures/posterior_predictive_mu_saturated_no_PolC_input_theta4_DmutS3610.rds
	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_no_PolC_DmutS3610.R
	
Saturation_DmutS3610_pdf: Reports/Figures/Mu_saturated_posterior_theta4_reparam_DmutS3610.pdf Reports/Figures/posterior_predictive_check_mu_saturated_DmutS3610.pdf Reports/Figures/mu_correlation_saturation_model_DmutS3610.pdf Reports/Figures/posterior_predictive_check_mu_saturated_no_PolC_input_theta4_DmutS3610.pdf Reports/Figures/Mu_saturated_posterior_theta4_DmutS3610.pdf

Saturation_DmutS3610: Reports/Saves_for_figures/mcmc_chain_Mu_saturation.csv Saturation_DmutS3610_pdf

################## PolC from MMR_DmutS3610

Reports/Saves_for_figures/jagsfit_Mu_PolC_from_MMR_DmutS3610.rds: Reports/Scripts_for_figures/compute_fit_EstimateMu_PolC_from_MMR_DmutS3610.R
	Rscript Reports/Scripts_for_figures/compute_fit_EstimateMu_PolC_from_MMR_DmutS3610.R
	
Reports/Saves_for_figures/posterior_predictive_mu_PolC_from_MMR_DmutS3610.rds: Reports/Scripts_for_figures/compute_posterior_predictive_mu_PolC_from_MMR_DmutS3610.R Reports/Saves_for_figures/jagsfit_Mu_PolC_from_MMR_DmutS3610.rds
	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_PolC_from_MMR_DmutS3610.R

Reports/Figures/prior_posterior_rho_PolC_from_MMR_DmutS3610.pdf: Reports/Scripts_for_figures/plot_prior_posterior_rho_PolC_from_MMR_DmutS3610.R Reports/Saves_for_figures/jagsfit_Mu_PolC_from_MMR_DmutS3610.rds
	Rscript Reports/Scripts_for_figures/plot_prior_posterior_rho_PolC_from_MMR_DmutS3610.R

Reports/Figures/posterior_predictive_check_mu_PolC_from_MMR_DmutS3610.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_PolC_from_MMR_DmutS3610.R Reports/Saves_for_figures/posterior_predictive_mu_PolC_from_MMR_DmutS3610.rds Reports/Scripts_for_figures/n_samples_predictive_check.R
	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_PolC_from_MMR_DmutS3610.R

PolC_from_MMR_DmutS3610_pdf: Reports/Figures/prior_posterior_rho_PolC_from_MMR_DmutS3610.pdf Reports/Figures/posterior_predictive_check_mu_PolC_from_MMR_DmutS3610.pdf

################# Transcription, transversion, insertion, deletion

Reports/Saves_for_figures/raw_data_ts_tv_indel.csv: Reports/Scripts_for_figures/save_data_ts_tv_indel.R
	Rscript Reports/Scripts_for_figures/save_data_ts_tv_indel.R  

########### GCM

Reports/Saves_for_figures/jagsfit_Mu_ts_tv_in_del_GCM.rds:  Reports/Scripts_for_figures/compute_fit_EstimateMu_ts_tv_in_del_GCM.R
	Rscript Reports/Scripts_for_figures/compute_fit_EstimateMu_ts_tv_in_del_GCM.R

Reports/Saves_for_figures/mcmc_chain_Mu_ts_tv_in_del_GCM.csv: Reports/Saves_for_figures/jagsfit_Mu_ts_tv_in_del_GCM.rds Reports/Scripts_for_figures/SaveChain_Mu_ts_tv_in_del_GCM.R
	Rscript Reports/Scripts_for_figures/SaveChain_Mu_ts_tv_in_del_GCM.R

Reports/Figures/mutation_rates_ts_tv_in_del_GCM.pdf: Reports/Scripts_for_figures/plot_ts_tv_ind_del_GCM.R Reports/Saves_for_figures/jagsfit_Mu_ts_tv_in_del_GCM.rds
	Rscript Reports/Scripts_for_figures/plot_ts_tv_ind_del_GCM.R

Reports/Figures/GCM_reparam_posterior_gamma_ts_tv_in_del.pdf: Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better_ts_tv_in_del.R Reports/Saves_for_figures/jagsfit_Mu_ts_tv_in_del_GCM.rds
	Rscript Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better_ts_tv_in_del.R

Reports/Figures/GCM_reparam_posterior_y_ts_tv_in_del.pdf: Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better_ts_tv_in_del.R Reports/Saves_for_figures/jagsfit_Mu_ts_tv_in_del_GCM.rds
	Rscript Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better_ts_tv_in_del.R

Reports/Saves_for_figures/posterior_predictive_mu_GCM_ts_tv_in_del.rds: Reports/Scripts_for_figures/compute_posterior_predictive_mu_GCM_ts_tv_in_del.R Reports/Saves_for_figures/jagsfit_Mu_ts_tv_in_del_GCM.rds Reports/Scripts_for_figures/n_samples_predictive_check.R
	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_GCM_ts_tv_in_del.R

Reports/Figures/posterior_predictive_check_mu_GCM_ts_tv_in_del.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_GCM_ts_tv_in_del.R Reports/Saves_for_figures/posterior_predictive_mu_GCM_ts_tv_in_del.rds
	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_GCM_ts_tv_in_del.R

ts_tv_in_del_GCM_pdf: Reports/Figures/mutation_rates_ts_tv_in_del_GCM.pdf Reports/Figures/GCM_reparam_posterior_gamma_ts_tv_in_del.pdf Reports/Figures/GCM_reparam_posterior_y_ts_tv_in_del.pdf Reports/Figures/posterior_predictive_check_mu_GCM_ts_tv_in_del.pdf

########### Saturation

Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_indel.rds:  Reports/Scripts_for_figures/compute_fit_EstimateMuSaturated_ts_tv_in_del.R
	Rscript Reports/Scripts_for_figures/compute_fit_EstimateMuSaturated_ts_tv_in_del.R

Reports/Saves_for_figures/mcmc_chain_Mu_ts_tv_in_del_saturation.csv: Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_indel.rds Reports/Scripts_for_figures/SaveChain_Mu_ts_tv_in_del_saturation.R
	Rscript Reports/Scripts_for_figures/SaveChain_Mu_ts_tv_in_del_saturation.R
	
Reports/Figures/mutation_rates_ts_tv_in_del_saturation.pdf: Reports/Scripts_for_figures/plot_ts_tv_ind_del_saturation.R Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_indel.rds
	Rscript Reports/Scripts_for_figures/plot_ts_tv_ind_del_saturation.R

Reports/Figures/Mu_saturated_posterior_theta4_ts_tv_ind_del.pdf: Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_indel.rds Reports/Scripts_for_figures/plot_posterior_theta4_mu_saturated_ts_tv_ind_del.R
	Rscript Reports/Scripts_for_figures/plot_posterior_theta4_mu_saturated_ts_tv_ind_del.R

Reports/Figures/Mu_saturated_posterior_theta4_reparam_ts_tv_in_del.pdf: Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_indel.rds Reports/Scripts_for_figures/plot_posterior_theta4_reparam_mu_saturated_ts_tv_in_del.R
	Rscript Reports/Scripts_for_figures/plot_posterior_theta4_reparam_mu_saturated_ts_tv_in_del.R	

Reports/Saves_for_figures/posterior_predictive_mu_saturated_ts_tv_in_del.rds: Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_indel.rds Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_ts_tv_in_del.R Reports/Scripts_for_figures/n_samples_predictive_check.R
	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_ts_tv_in_del.R
	
Reports/Figures/posterior_predictive_check_mu_saturated_ts_tv_in_del.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_ts_tv_in_del.R Reports/Saves_for_figures/posterior_predictive_mu_saturated_ts_tv_in_del.rds
	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_ts_tv_in_del.R	

Reports/Saves_for_figures/posterior_predictive_mu_saturated_no_PolC_input_theta4_ts_tv_in_del.rds: Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_no_PolC_ts_tv_in_del.R Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_indel.rds Reports/Scripts_for_figures/n_samples_predictive_check.R
	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_no_PolC_ts_tv_in_del.R	

Reports/Figures/posterior_predictive_check_mu_saturated_no_PolC_input_theta4_ts_tv_in_del.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_no_PolC_ts_tv_in_del.R Reports/Saves_for_figures/posterior_predictive_mu_saturated_no_PolC_input_theta4_ts_tv_in_del.rds
	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_no_PolC_ts_tv_in_del.R

ts_tv_in_del_pdf: ts_tv_in_del_GCM_pdf Reports/Figures/mutation_rates_ts_tv_in_del_saturation.pdf Reports/Figures/Mu_saturated_posterior_theta4_reparam_ts_tv_in_del.pdf Reports/Figures/posterior_predictive_check_mu_saturated_ts_tv_in_del.pdf Reports/Figures/posterior_predictive_check_mu_saturated_no_PolC_input_theta4_ts_tv_in_del.pdf Reports/Figures/Mu_saturated_posterior_theta4_ts_tv_ind_del.pdf
ts_tv_in_del: Reports/Saves_for_figures/raw_data_ts_tv_indel.csv Reports/Saves_for_figures/mcmc_chain_Mu_ts_tv_in_del_GCM.csv Reports/Saves_for_figures/mcmc_chain_Mu_ts_tv_in_del_saturation.csv ts_tv_in_del_pdf


########### GCM DmutS3610

Reports/Saves_for_figures/jagsfit_Mu_ts_tv_GCM_DmutS3610.rds:  Reports/Scripts_for_figures/compute_fit_EstimateMu_ts_tv_GCM_DmutS3610.R
	Rscript Reports/Scripts_for_figures/compute_fit_EstimateMu_ts_tv_GCM_DmutS3610.R

Reports/Saves_for_figures/mcmc_chain_Mu_ts_tv_GCM_DmutS3610.csv: Reports/Saves_for_figures/jagsfit_Mu_ts_tv_GCM_DmutS3610.rds Reports/Scripts_for_figures/SaveChain_Mu_ts_tv_GCM_DmutS3610.R
	Rscript Reports/Scripts_for_figures/SaveChain_Mu_ts_tv_GCM_DmutS3610.R

Reports/Figures/mutation_rates_ts_tv_GCM_DmutS3610.pdf: Reports/Scripts_for_figures/plot_ts_tv_GCM_DmutS3610.R Reports/Saves_for_figures/jagsfit_Mu_ts_tv_GCM_DmutS3610.rds
	Rscript Reports/Scripts_for_figures/plot_ts_tv_GCM_DmutS3610.R

#Reports/Figures/GCM_reparam_posterior_gamma_ts_tv_in_del.pdf: Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better_ts_tv_in_del.R Reports/Saves_for_figures/jagsfit_Mu_ts_tv_in_del_GCM.rds
#	Rscript Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better_ts_tv_in_del.R

#Reports/Figures/GCM_reparam_posterior_y_ts_tv_in_del.pdf: Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better_ts_tv_in_del.R Reports/Saves_for_figures/jagsfit_Mu_ts_tv_in_del_GCM.rds
#	Rscript Reports/Scripts_for_figures/plot_GCM_reparam_posterior_better_ts_tv_in_del.R

#Reports/Saves_for_figures/posterior_predictive_mu_GCM_ts_tv_in_del.rds: Reports/Scripts_for_figures/compute_posterior_predictive_mu_GCM_ts_tv_in_del.R Reports/Saves_for_figures/jagsfit_Mu_ts_tv_in_del_GCM.rds Reports/Scripts_for_figures/n_samples_predictive_check.R
#	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_GCM_ts_tv_in_del.R

#Reports/Figures/posterior_predictive_check_mu_GCM_ts_tv_in_del.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_GCM_ts_tv_in_del.R Reports/Saves_for_figures/posterior_predictive_mu_GCM_ts_tv_in_del.rds
#	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_GCM_ts_tv_in_del.R

#ts_tv_in_del_GCM_pdf: Reports/Figures/mutation_rates_ts_tv_in_del_GCM.pdf Reports/Figures/GCM_reparam_posterior_gamma_ts_tv_in_del.pdf Reports/Figures/GCM_reparam_posterior_y_ts_tv_in_del.pdf Reports/Figures/posterior_predictive_check_mu_GCM_ts_tv_in_del.pdf

########### Saturation DmutS3610

Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_DmutS3610.rds:  Reports/Scripts_for_figures/compute_fit_EstimateMuSaturated_ts_tv_DmutS3610.R
	Rscript Reports/Scripts_for_figures/compute_fit_EstimateMuSaturated_ts_tv_DmutS3610.R

Reports/Saves_for_figures/mcmc_chain_Mu_ts_tv_DmutS3610_saturation.csv: Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_DmutS3610.rds Reports/Scripts_for_figures/SaveChain_Mu_ts_tv_DmutS3610_saturation.R
	Rscript Reports/Scripts_for_figures/SaveChain_Mu_ts_tv_DmutS3610_saturation.R
	
Reports/Figures/mutation_rates_ts_tv_DmutS3610_saturation.pdf: Reports/Scripts_for_figures/plot_ts_tv_DmutS3610_saturation.R Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_DmutS3610.rds
	Rscript Reports/Scripts_for_figures/plot_ts_tv_DmutS3610_saturation.R

#Reports/Figures/Mu_saturated_posterior_theta4_ts_tv_ind_del.pdf: Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_indel.rds Reports/Scripts_for_figures/plot_posterior_theta4_mu_saturated_ts_tv_ind_del.R
#	Rscript Reports/Scripts_for_figures/plot_posterior_theta4_mu_saturated_ts_tv_ind_del.R

#Reports/Figures/Mu_saturated_posterior_theta4_reparam_ts_tv_in_del.pdf: Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_indel.rds Reports/Scripts_for_figures/plot_posterior_theta4_reparam_mu_saturated_ts_tv_in_del.R
#	Rscript Reports/Scripts_for_figures/plot_posterior_theta4_reparam_mu_saturated_ts_tv_in_del.R	

#Reports/Saves_for_figures/posterior_predictive_mu_saturated_ts_tv_in_del.rds: Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_indel.rds Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_ts_tv_in_del.R Reports/Scripts_for_figures/n_samples_predictive_check.R
#	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_ts_tv_in_del.R
	
#Reports/Figures/posterior_predictive_check_mu_saturated_ts_tv_in_del.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_ts_tv_in_del.R Reports/Saves_for_figures/posterior_predictive_mu_saturated_ts_tv_in_del.rds
#	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_ts_tv_in_del.R	

#Reports/Saves_for_figures/posterior_predictive_mu_saturated_no_PolC_input_theta4_ts_tv_in_del.rds: Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_no_PolC_ts_tv_in_del.R Reports/Saves_for_figures/jagsfit_Mu_saturated_ts_tv_indel.rds Reports/Scripts_for_figures/n_samples_predictive_check.R
#	Rscript Reports/Scripts_for_figures/compute_posterior_predictive_mu_saturated_no_PolC_ts_tv_in_del.R	

#Reports/Figures/posterior_predictive_check_mu_saturated_no_PolC_input_theta4_ts_tv_in_del.pdf: Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_no_PolC_ts_tv_in_del.R Reports/Saves_for_figures/posterior_predictive_mu_saturated_no_PolC_input_theta4_ts_tv_in_del.rds
#	Rscript Reports/Scripts_for_figures/plot_posterior_predictive_mu_saturated_no_PolC_ts_tv_in_del.R

#ts_tv_in_del_pdf: ts_tv_in_del_GCM_pdf Reports/Figures/mutation_rates_ts_tv_in_del_saturation.pdf Reports/Figures/Mu_saturated_posterior_theta4_reparam_ts_tv_in_del.pdf Reports/Figures/posterior_predictive_check_mu_saturated_ts_tv_in_del.pdf Reports/Figures/posterior_predictive_check_mu_saturated_no_PolC_input_theta4_ts_tv_in_del.pdf Reports/Figures/Mu_saturated_posterior_theta4_ts_tv_ind_del.pdf
#ts_tv_in_del: Reports/Saves_for_figures/raw_data_ts_tv_indel.csv Reports/Saves_for_figures/mcmc_chain_Mu_ts_tv_in_del_GCM.csv Reports/Saves_for_figures/mcmc_chain_Mu_ts_tv_in_del_saturation.csv ts_tv_in_del_pdf


#################################

all: GCM Saturation PolC_from_MMR_pdf Reports/Saves_for_figures/raw_mutation_accumulation_data_Irene.csv GCM_DmutS3610 Saturation_DmutS3610 PolC_from_MMR_DmutS3610_pdf ts_tv_in_del

clean: 
	rm -rf Reports/Saves_for_figures/* Reports/Figures/*
